function [rec_img] = reconstruct_bp(model, K, sinogram)
% Perform backprojection reconstruction with the parameters that are specified in the provided model.

% Ho modificato i parametri in inpur aggiungendo la posizione dei
% trasduttori per poter calcolare T 
rec_img = backproject_waveeq(...
    sinogram,...
    model.Discretization.region.xPositionsFov, ...
    model.Discretization.region.zPositionsFov,...
    model.Probe.detector.xPositionsOfTransducers, ...
    model.Probe.detector.zPositionsOfTransducers, ...
    model.Medium.speedOfSound, ...
    model.Probe.DAC.frequency,...
    model.DataPreprocessing.numCroppedSamplesAtSinogramStart + model.Probe.DAC.delayBeforeRecording,...
    model.Probe.detector.angularCoverage,...
    model.Probe.detector.radius,...
    1,...
    K);
rec_img = fliplr(rec_img);

end

